import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { diagnosis } from '../plugins/just-vibe/scripts/lib/diagnosis.mjs';
import { assistantRuntime } from '../plugins/just-vibe/scripts/lib/assistant-runtime.mjs';
import { assistantHook } from '../plugins/just-vibe/scripts/lib/assistant-hooks.mjs';
import { adaptiveStore } from '../plugins/just-vibe/scripts/lib/adaptive-store.mjs';
test('diagnosis separates configuration, hook delivery, selection, loading and tool observations', t => {
 const dir=mkdtempSync(join(tmpdir(),'jv-diagnosis-')),root=join(dir,'app'),options={home:join(dir,'home')};mkdirSync(root);writeFileSync(join(root,'app.mjs'),'export const x = 1;');t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const status=()=>diagnosis(root,'status',{host:'codex'},options).stages.map(s=>s.observed);
 assert.deepEqual(status(),[false,false,false,false]);
 const task=assistantRuntime(root,'start',{brief:'Fix app.mjs bug',host:'codex',sessionId:'direct'},options);
 assert.deepEqual(status(),[false,false,false,false]);
 assistantHook({cwd:root,session_id:'native',hook_event_name:'UserPromptSubmit',prompt:'Fix app.mjs bug'}, {...options,host:'codex'});
 assert.deepEqual(status(),[true,false,false,false]);
 assistantRuntime(root,'select',{taskId:task.id,workflows:['fix'],mode:'apply',reason:'Repair the requested bug'},options);
 assistantRuntime(root,'load',{taskId:task.id,workflow:'fix'},options);
 assert.deepEqual(status(),[true,true,true,false]);
 const store=adaptiveStore(root,options),native=store.read(store.sessionPath('codex','native'));
 assistantHook({cwd:root,session_id:'native',hook_event_name:'PostToolUse',tool_name:'Read',tool_input:{file_path:join(root,'app.mjs')},tool_response:'fixture'}, {...options,host:'codex'});
 assert.deepEqual(status(),[true,true,true,true]);assert.ok(native.taskId);
 assert.throws(()=>diagnosis(root,'trial',{host:'codex'},options),/useAccount/);
});
