import { canvasClient } from './canvas-client.mjs';

export function renderCanvas(nonce) {
  if (!/^[a-f0-9]+$/.test(nonce)) throw Error('Invalid script nonce.');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plan review · just-vibe</title>
<style>
:root{color-scheme:light;font-family:system-ui,sans-serif;color:#282922;background:#f5f3ed;font-size:16px}*{box-sizing:border-box}body{margin:0}button,textarea{font:inherit}button{cursor:pointer;border:1px solid #9c9d90;border-radius:6px;padding:.65rem .9rem;color:inherit;background:transparent}button:hover{background:#e7e6db}button:disabled{cursor:default;opacity:.55}button:focus-visible,textarea:focus-visible,a:focus-visible{outline:3px solid #536946;outline-offset:3px}header{padding:2rem 3vw;border-bottom:1px solid #d1d1c6;display:flex;justify-content:space-between;gap:1.5rem;align-items:center}header p{margin:0;color:#54564c}h1{font:400 clamp(1.8rem,4vw,3rem)/1.12 Georgia,serif;margin:.4rem 0}h2{font:400 1.5rem Georgia,serif;margin:0 0 1rem}main{display:grid;grid-template-columns:minmax(0,1fr) minmax(290px,360px);gap:3vw;max-width:1600px;margin:auto;padding:2rem 3vw}article,aside{min-width:0}.paper{background:#fffefa;border:1px solid #d1d1c6;border-radius:8px;padding:1.25rem;overflow:auto;max-height:74vh}.line{display:flex;align-items:flex-start;gap:1rem}.line button{flex:none;width:3rem;padding:.3rem .1rem;border-color:transparent;font-size:.8rem;color:#66695b}.line button[aria-pressed=true]{background:#e2e7d5;border-color:#82906d}.line code{white-space:pre-wrap;overflow-wrap:anywhere;min-width:0;line-height:1.7;font:inherit}.toolbar,.actions{display:flex;flex-wrap:wrap;gap:.6rem;align-items:center;margin-bottom:1rem}#path{font-size:.85rem;overflow-wrap:anywhere;color:#54564c}.hint{font-size:.88rem;line-height:1.6;color:#54564c}label{display:block;margin:1rem 0 .5rem}textarea{width:100%;min-height:130px;resize:vertical;line-height:1.5;padding:.8rem;border:1px solid #9c9d90;border-radius:6px;background:#fffefa}.actions{margin:1rem 0}.primary{background:#303b29;color:#fffefa;border-color:#303b29}.primary:hover{background:#435239}#status{max-width:34rem;line-height:1.6;overflow-wrap:anywhere}#error{color:#922c24;white-space:pre-wrap}#feedback{list-style:none;margin:0;padding:0}#feedback li{border-top:1px solid #d1d1c6;padding:1rem 0}#feedback p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.6;margin:.4rem 0}#feedback small{color:#54564c}iframe{width:100%;height:70vh;border:0;background:white}[hidden]{display:none!important}.review-history{margin-top:2rem}footer{padding:1rem 3vw;color:#54564c;font-size:.85rem} @media(max-width:850px){header{display:block}header #status{margin-top:1rem}main{grid-template-columns:1fr;padding:1.5rem 4vw;gap:2rem}.paper{max-height:60vh}h1{overflow-wrap:anywhere}}@media(prefers-reduced-motion:no-preference){button{transition:background .15s,border-color .15s}}
</style></head><body><header><div><p>just-vibe / review</p><h1 id="title">Plan review</h1><p id="path"></p></div><p id="status" role="status" aria-live="polite">Loading review…</p></header><main><article aria-label="Artifact"><div class="toolbar"><button id="view" hidden>Preview HTML</button><span class="hint">Select a line to annotate it.</span></div><div class="paper" id="document"></div><iframe id="preview" title="Sandboxed artifact preview" sandbox="" hidden></iframe></article><aside><section aria-labelledby="review-title"><h2 id="review-title">Your review</h2><p class="hint">Feedback applies to the version shown here. Approval records your review; it does not deploy, publish, or authorize unrelated actions.</p><p id="anchor" class="hint">Comment on the whole document.</p><button id="clear" hidden>Clear line selection</button><label for="message">Feedback or review reason</label><textarea id="message" placeholder="What should change, or why is this ready?"></textarea><div class="actions"><button id="comment">Add comment</button><button id="changes">Request changes</button><button id="approve" class="primary">Approve version</button></div><p id="error" role="alert"></p></section><section class="review-history" aria-labelledby="history-title"><h2 id="history-title">Conversation</h2><ul id="feedback"></ul></section></aside></main><footer>Private local review. Close this tab when finished; the server expires automatically.</footer>
<script nonce="${nonce}">(${canvasClient.toString()})();
</script></body></html>`;
}
