// Intent rules add workflows that a request's words may not name. Action rules say what
// kind of work is requested (review, test, teach, decide, verify); topic rules say which
// domain it touches. When an action rule fires, topic rules only break ties, so "review my
// changes before I commit" stays a review and "write tests for the password reset flow"
// stays testing. Topic rules require their domain signal: a component needs UI context, a
// migration needs a database, a Vercel build needs Vercel.
//
// Rule fields: test (RegExp), ids (ordered workflows), boost (default 45), action, damp
// (mode lead: dampens topics without selecting much), unlessText (skip when present),
// name/unlessRules (skip when a more specific named rule matched), reason.

// A clear outer rewrite request owns routing. Embedded workflow names and actions
// are source text, not explicit selection or authority to perform those actions.
export const promptRewrite = /^(?:(?:please|can you|could you|would you)\s+)*(?:reprompt\b|make\s+(?:this|my|the)\s+prompt\s+better\b|(?:improve|rewrite|rephrase|clarify|strengthen|tighten)\s+(?:(?:this|that|my|the|following|previous|last|our|earlier|original)\s+){0,2}prompt(?=\s*(?:$|[:.!?\n]|\b(?:for|with|using|to|so|without|and|by|in|only)\b))|(?:improve|rewrite)\s+this\s+for\s+(?:another|a\s+different)\s+(?:ai|agent|session|model)\b)/i;

// Metric names are not pull requests.
export const ruleText = text => text.replace(/[‘’ʼ]/g, '\'').replace(/\bpr[-\s]?auc\b|\bpr\s+curves?\b|\bprecision[-\s]recall\b/gi, 'prauc');

const SERVER_WORDS = /\b(?:sql|query|queries|endpoint|api|database|db|job|script|pandas|spark|report|index|cluster|backend|server|dataframe|warehouse)\b/i;

export const intents = [
  // Actions: the kind of work requested.
  { name: 'quiz', action: true, test: /^(?:please\s+)?(?:quiz\s+me|test\s+me|test\s+my\s+understanding)\b/i, ids: ['teach-test'], reason: 'Assess understanding with questions' },
  { name: 'teach', action: true, test: /^(?:please\s+)?(?:teach\b|help\s+me\s+(?:learn|understand)|i\s+(?:want|need)\s+to\s+(?:learn|understand)|give\s+me\s+a\s+lesson|lesson\s+on)\b|\b(?:teach\s+me|help\s+me\s+learn|learn\s+(?:about|how)\s+|walk\s+me\s+through\s+how)\b/i, ids: ['teach', 'explain'], reason: 'Teach a concept or practice' },
  { name: 'explain', action: true, test: /^(?:please\s+)?(?:explain|walk\s+me\s+through|how\s+does|how\s+do|what\s+does)\b/i, unlessText: /\b(?:predictions?|feature\s+importance|shap|query\s+plan|explain\s+analyze|execution\s+plan)\b/i, ids: ['explain', 'trace'], reason: 'Explain existing code or behavior' },
  { name: 'locate', action: true, test: /\b(?:which|what)\s+(?:file|module|function|class|component|method|part\s+of\s+the\s+code)\s+(?:handles?|does|is\s+responsible|owns|defines|implements|controls)\b|\bwhere\s+(?:is|are|does|do)\s+(?:\w+\s+){0,4}(?:handled|defined|implemented|set|called|computed|stored)\b/i, ids: ['explain', 'trace'], reason: 'Locate and explain existing code' },
  { name: 'review', action: true, test: /\b(?:review|look\s+over|go\s+over|check)\s+(?:\w+\s+){0,2}(?:changes|diff|code|branch|commits?|implementation|patch)\b/i, ids: ['review'], reason: 'Review code changes' },
  { name: 'review-pr', action: true, test: /\b(?:review|look\s+over|go\s+over|check)\s+(?:\w+\W+){0,3}(?:pr|pull\s+request)\b|\bpr\s*#\d+|\/pull\/\d+/i, unlessText: /\b(?:description|title|body|summary|blurb)\b/i, ids: ['github-review'], reason: 'Review a pull request' },
  { name: 'regression-test', action: true, test: /\bregression\s+tests?\b|\btests?\s+(?:for|covering|that\s+catches)\s+(?:the|this|that)\s+(?:\w+\s+)?(?:bug|regression|fix)\b|\bso\s+it\s+(?:can(?:'t|not)|doesn't|won't)\s+come\s+back\b/i, ids: ['test-regression'], reason: 'Lock a fixed bug in with a test' },
  { name: 'tests', unlessRules: ['regression-test'], action: true, test: /\b(?:write|add|create)\s+(?:\w+\s+){0,3}(?:tests?|specs?|test\s+cases)\b/i, ids: ['test'], reason: 'Add or improve tests' },
  { name: 'verify', action: true, test: /\b(?:make\s+sure|ensure|confirm|check\s+that|verify\s+that)\b[\s\S]*\b(?:pass(?:es)?|still\s+works?|works?|green)\b|\brun\s+(?:all\s+)?the\s+(?:checks|tests)\b/i, ids: ['verify'], reason: 'Verify the requested outcome' },
  { name: 'compare', action: true, test: /^(?:please\s+)?(?:compare|contrast)\b(?=[\s\S]*\b(?:approach\w*|options?|librar\w*|frameworks?|tools?|implementations?|architectures?|strategies|solutions?|alternatives?|designs?\s+for)\b)|\bdifferences?\s+between\s+(?:\w+\s+){0,3}(?:and|vs\.?|versus)\b|\bpros\s+and\s+cons\b|^[^.?!\n]{0,60}\b(?:vs\.?|versus)\b[^.?!\n]{0,60}\?/i, unlessText: /\bbuy\b[\s\S]*\bbuild\b|\bbuild\b[\s\S]*\bbuy\b|\b(?:design|mockup|figma|screenshot|comp|reference)\b[\s\S]*\b(?:fix|close|match)\s+(?:the\s+|any\s+)?(?:differences?|gaps?|it)\b/i, ids: ['compare', 'decide'], reason: 'Compare named options' },
  { test: /\b(?:design|mockup|figma|screenshot|comp|reference)\b[\s\S]*\b(?:fix|close)\s+(?:the\s+|any\s+)?(?:differences?|gaps?)\b|\bmatch\s+(?:the\s+|our\s+|this\s+)?(?:design|mockup|figma|screenshot|comp)\b/i, ids: ['match'], reason: 'Close gaps against a visual reference' },
  { name: 'buy-build', action: true, test: /\bbuy\b[\s\S]*\b(?:build|in-house)\b|\b(?:build|in-house)\b[\s\S]*\bbuy\b|\b(?:vendor|saas|off-the-shelf)\b[\s\S]*\b(?:or|versus|vs\.?)\b[\s\S]*\b(?:build|ourselves|in-house)\b/i, ids: ['decision-buy-build', 'decide'], reason: 'Buy versus build decision' },
  { name: 'decide', action: true, unlessRules: ['decision-revisit'], test: /\b(?:should\s+(?:we|i)\s+(?:use|pick|choose|go\s+with|adopt|switch)|which\s+(?:\w+\s+){0,3}(?:should|to\s+use|to\s+choose|to\s+pick|is\s+better)|choose\s+between|pick\s+(?:one|between)|trade.?offs?\s+(?:between|of\s+(?:using|choosing|picking|adopting))|decide\s+(?:between|whether|on))/i, ids: ['decide'], reason: 'A decision between named options' },
  { name: 'discover', action: true, test: /\b(?:which|what)\s+(?:just-vibe\s+|jv\s+)?(?:command|workflow|skill)s?\b|\bwhat\s+can\s+(?:just-vibe|you)\s+do\b|\blist\s+(?:the\s+|all\s+)?(?:just-vibe\s+)?(?:commands|workflows|skills)\b/i, ids: ['help', 'tools'], reason: 'Find the right just-vibe workflow' },
  { name: 'refactor', action: true, test: /\b(?:split|break\s+up|extract|restructure|reorganize|decouple)\b[\s\S]*\b(?:files?|modules?|class(?:es)?|functions?|components?|services?)\b[\s\S]*\b(?:into|smaller|separate|own)\b/i, unlessText: /\b(?:commits?|chunks?|bundles?|dataset|train\w*|split\s+(?:the\s+)?data)\b/i, ids: ['refactor'], reason: 'Restructure code while preserving behavior' },
  { name: 'skill', action: true, test: /\b(?:create|write|make|build|author|improve)\s+(?:(?:a|an|the|new|reusable|custom|my|our)\s+){0,3}(?:skill|slash\s+command|custom\s+command)s?\b/i, ids: ['skill'], reason: 'Author a reusable workflow skill' },
  { name: 'bisect', action: true, test: /\b(?:which|what)\s+commit\b|\bfirst\s+bad\s+commit\b|\bwhen\s+did\s+(?:this|it)\s+(?:break|start)/i, ids: ['git-bisect'], reason: 'Find the change that introduced a regression' },
  { name: 'orient', action: true, test: /\b(?:layout|structure|organi[sz]ation|stack)\s+of\s+(?:this|the)\s+(?:repo|repository|codebase|project)\b|\b(?:folder|project|repo|directory|codebase)\s+(?:structure|layout)\b|\b(?:new\s+to\s+(?:this|the)\s+(?:repo|codebase|project)|just\s+cloned|up\s+to\s+speed\s+on)\b/i, ids: ['orient'], reason: 'Orientation in an unfamiliar project' },
  // Mode lead: keeps domain keywords from overriding a planning request without forcing plan.
  { name: 'plan', damp: true, boost: 0, test: /^(?:please\s+)?(?:plan|draft\s+a\s+plan|make\s+a\s+plan|come\s+up\s+with\s+a\s+plan)\b|\bbefore\s+(?:writing|changing)\s+any\s+code\b/i, ids: ['plan'], reason: 'Plan before implementation' },

  // Topics: the domain the work touches.
  { test: /^(?:please\s+)?(?:fix|repair|correct)\b(?=[\s\S]*(?:\b(?:bug|defect|function|method|error|crash)\b|\.[cm]?[jt]sx?\b))/i, ids: ['fix'], boost: 25, reason: 'Repair an identified code defect and verify its behavior' },
  { test: /^(?:please\s+)?(?:add|build|implement|create|ship)\s+(?:(?:a|an|the|new|our|another)\s+){0,2}(?:[\w-]+\s+){0,2}(?:feature|button|page|endpoint|screen|export|settings\s+page|toggle|dark\s+mode|dashboard)\b/i, ids: ['build'], boost: 25, reason: 'Implement a feature' },
  { test: /\b(?:verify|check|test)\b[\s\S]*\b(?:visitor|user\s+journey|upload|playback|acceptance)\b/i, ids: ['agent-qa', 'verify'], reason: 'Verify an observable visitor outcome in the browser' },
  { action: true, test: /^(?:please\s+)?(?:fix|patch|remediate|close|mitigate)\b[\s\S]*\b(?:sql\s+injection|injection|xss|cross.site\s+scripting|csrf|ssrf|path\s+traversal|deserialization|vulnerabilit(?:y|ies)|idor|security\s+(?:bug|hole|issue))/i, ids: ['security-fix'], reason: 'Remediate a known vulnerability' },
  { test: /\b(?:sql\s+injection|(?:command|template|ldap|nosql|prompt)\s+injection|xss|cross.site\s+scripting|ssrf|path\s+traversal|(?:insecure\s+)?deserialization|unsafe\s+(?:input|concatenation))\b/i, ids: ['security-inputs', 'security'], reason: 'Untrusted input reaching an interpreter or resource' },
  { test: /\b(?:vulnerab\w*|cve\S*|advisor(?:y|ies)|npm\s+audit|snyk)\b[\s\S]*\b(?:dependenc\w*|packages?|librar\w*|lockfile|npm|pip)\b|\b(?:dependenc\w*|packages?|npm)\b[\s\S]*\b(?:vulnerab\w*|cve\S*|advisor\w*)|\bdependabot\b|\bnpm\s+audit\b/i, ids: ['security-dependencies'], reason: 'Vulnerable dependency' },
  { test: /\b(?:csrf|idor|bola|broken\s+(?:object|access)\s+\w+|access\s+control|authorization\s+bypass|missing\s+permission\s+checks?|chang\w*\s+the\s+id|guess\w*\s+(?:the\s+|an?\s+)?(?:\w+\s+)?ids?)\b|\b(?:see|view|read|access|open|edit|delete|modify|change|download)\s+(?:\w+\s+){0,3}(?:another|other|each\s+other)\W*(?:\w+\W+){0,1}(?:user|tenant|customer|company|organization|account|people|person)(?:s|'s)?\b/i, ids: ['security-authz', 'backend-permissions'], reason: 'Authorization boundary' },
  { test: /\b(?:leaked|exposed|committed|hardcoded|hard-coded|pushed)\s+(?:\w+\s+){0,3}(?:secrets?|keys?|tokens?|credentials?|passwords?)\b|\b(?:secrets?|keys?|tokens?|credentials?|passwords?)\s+(?:\w+\s+){0,2}(?:was|were|got|has\s+been|have\s+been)\s+(?:leaked|exposed|pushed|committed)\b|\bsecrets?\s+(?:in|from)\s+(?:the\s+)?(?:repo|git|history|code)\b|\b(?:api\s+keys?|passwords?|credentials?)\b[\s\S]*\b(?:repo|git|history|committed)\b/i, ids: ['security-secrets', 'security-fix'], reason: 'Exposed credential' },
  { test: /\b(?:vulnerab\w*|insecure|exploit\w*|attack\w*|pentest\w*|hack\w*|owasp|security\s+(?:review|audit|issues?|holes?|risks?))\b|\bis\s+(?:it|this|our\s+\w+)\s+(?:safe|secure)\b/i, ids: ['security'], reason: 'Security review' },
  { test: /\b(?:cors|content.security.policy|csp|security\s+headers?|hsts|cookie\s+flags?|samesite|httponly|access-control-allow-\w+)\b/i, ids: ['security-config'], reason: 'Security-relevant configuration' },
  { test: /\b(?:docker\w*|containers?|images?)\b[\s\S]*\b(?:build|fail\w*|broken|crash\w*|runtime|kubernetes|k8s)\b|\b(?:broken|fail\w*|crash\w*)\b[\s\S]*\b(?:docker\w*|containers?)\b/i, unlessText: /\b(?:img|jpe?g|png|svg|webp|avif|picture|photo|icon|thumbnail|image\s+(?:tag|upload|asset|component))\b/i, ids: ['ops-container'], reason: 'Container build or runtime diagnosis' },
  { test: /\b(?:mobile\s+menu|hamburger|navigation\s+menu|dropdown|popover|(?:menu|modal|drawer|dialog)\s+(?:stays?|won't|doesn't|does\s+not|never)\s+(?:open|close)|(?:loading|empty|error|failure|retry|partial|success|disabled|skeleton|pending)\s+(?:and\s+\w+\s+)?states?)\b/i, ids: ['ui-states', 'ui-responsive'], reason: 'UI interaction states' },
  { test: /\b(?:overlap\w*|overflow\w*)\b(?=[\s\S]*\b(?:footer|header|sidebar|button|text|modal|menu|nav\w*|card|image|page|screen|content|elements?|columns?|layout|tablets?|phones?|mobile)\b)|\b(?:responsive|breakpoints?|small\s+screens?|phones?|tablets?|mobile\s+(?:layout|view|width|screen|safari|chrome)|viewport|narrow\s+screens?|on\s+mobile)\b|\blayout\s+(?:breaks?|broken|shift\w*)\b|\b(?:page|mobile|grid|flex)\s+layout\b/i, ids: ['ui-responsive', 'ui-states'], reason: 'Viewport and layout behavior' },
  { test: /\b(?:spacing|typography|alignment|padding|margins?|visual\s+polish|looks?\s+(?:off|cheap|dated|unpolished|janky))\b/i, ids: ['polish', 'ui-system'], reason: 'Visual polish' },
  { test: /\b(?:training|loss|gradient)\b[\s\S]*\b(?:unstable|diverg\w*|nan|explod\w*|plateau\w*|flat|stuck|not\s+(?:decreasing|improving|converging))|\b(?:unstable|diverg|nan|explod)\w*\b[\s\S]*\b(?:training|loss|gradient)\b|\bnot\s+learning\b/i, ids: ['ml-debug-training'], reason: 'Training stability diagnosis' },
  { test: /\b(?:address|resolve|fix|respond\s+to)\b[\s\S]*\b(?:pr|pull\s+request|review)\b[\s\S]*\b(?:feedback|comments?|requests?|suggestions?)\b|\b(?:pr|pull\s+request)\b[\s\S]*\bfeedback\b|\breviewer\s+(?:asked|requested|wants)\b/i, ids: ['github-address-review'], reason: 'Requested pull request feedback' },
  { test: /^(?:please\s+)?(?:undo|revert|reverse)\b|\bundo\s+(?:the|my|that|last|those)\s+(?:\w+\s+)?(?:task|changes?|edits?)\b/i, unlessText: /\b(?:proxy|commit|migration|deploy\w*|release|later|decision)\b/i, ids: ['undo'], reason: 'Selective local task reversal' },
  { name: 'decision-revisit', test: /\b(?:revisit|reconsider|reassess|re-?evaluate)\b[\s\S]{0,40}\bdecisions?\b|\bdecisions?\b[\s\S]{0,40}\b(?:revisit|reconsider|reassess|re-?evaluate)\b/i, ids: ['decision-revisit', 'decide'], reason: 'Review a prior decision against current facts' },
  { test: /\bsave\s+(?:this|the|our)\s+decision\b|\bremind\w*\s+(?:me\s+|us\s+)?(?:if|when)\b[\s\S]*\b(?:pass\w*|exceed\w*|reach\w*|drop\w*|goes\s+(?:over|above|below))\b/i, ids: ['decide', 'decision-adr'], reason: 'Record a decision with reconsideration triggers' },
  { test: /\b(?:hard|easy|possible|costly)\s+to\s+(?:undo|reverse|change\s+later)\b|\b(?:one-way\s+door|two-way\s+door|lock-?in|locked\s+in|reversib\w*|exit\s+cost)\b/i, ids: ['decision-reversible'], reason: 'Reversibility of a decision' },
  { test: /\b(?:build|implement|try)\b[\s\S]*\b(?:alternatives|variants|two\s+versions|three\s+versions)\b/i, ids: ['compare'], reason: 'Working alternatives with common requirements' },
  { test: /\b(?:exercise|practice)\b[\s\S]*\b(?:project|repo|code)\b/i, ids: ['teach'], reason: 'Hands-on project learning' },
  { test: /\b(?:mlflow|wandb|w&b)\b[\s\S]*\b(?:compare|export|runs?|metrics)\b|\bcompare\b[\s\S]*\b(?:mlflow|wandb)\b/i, ids: ['ml-evaluate'], reason: 'Recorded ML experiment comparison' },
  { test: /\b(?:evidence\s+report|acceptance\s+report|requirement-linked)\b/i, ids: ['verify'], reason: 'Requirement-linked verification evidence' },
  { test: /\b(?:claude|agents)\.md\b|\b(?:save|remember|persist|preserve)\b[\s\S]*\b(?:conversation|project\s+instructions|context|decisions|corrections)\b/i, ids: ['remember'], reason: 'Durable project instructions from conversation context' },
  // CI is provider-neutral unless GitHub is named; "checks" or "actions" alone are not CI.
  { name: 'ci-github', test: /\b(?:github\s+actions?|workflow\s+runs?|pr\s+checks|checks\s+on\s+(?:my|the|this)\s+(?:pr|pull\s+request)|actions\s+(?:run|job|workflow))\b[\s\S]*\b(?:fail\w*|broken|red|errors?)\b|\b(?:fail\w*|broken|red)\b[\s\S]*\b(?:github\s+actions?|workflow\s+runs?|pr\s+checks)\b/i, ids: ['github-fix-ci', 'github-actions'], reason: 'Failing GitHub checks' },
  { unlessRules: ['ci-github'], test: /\b(?:ci|pipeline|jenkins|gitlab|circleci|buildkite|azure\s+pipelines|build\s+server)\b[\s\S]*\b(?:fail\w*|broken|red|timing\s+out|times?\s+out)\b|\b(?:fail\w*|broken|red)\b[\s\S]*\b(?:ci|pipeline|jenkins|gitlab|circleci|buildkite)\b/i, unlessText: /\b(?:data\s+pipeline|etl|dag|airflow|dbt)\b/i, ids: ['ci', 'github-fix-ci'], reason: 'Failing CI pipeline' },
  { test: /\bflaky\b|\b(?:intermittent\w*|randomly\s+fail\w*|sometimes\s+(?:fail\w*|pass\w*)|fails?\s+(?:sometimes|randomly|intermittently|only\s+in\s+ci))\b(?=[\s\S]*\b(?:tests?|specs?|ci|jest|pytest|vitest|playwright|cypress|suite)\b)|\b(?:tests?|specs?|suite)\b[\s\S]*\b(?:intermittent\w*|randomly\s+fail\w*|sometimes\s+(?:fail\w*|pass\w*)|times?\s+out\s+intermittently)\b/i, ids: ['test-flaky'], reason: 'Intermittent failure' },
  { test: /\b(?:oauth|login|logout|signin|sign\s+in|log\s+in|password\s+reset|authentication|(?:token|session|jwt|cookie)\W+(?:\w+\W+){0,3}(?:refresh|expir\w*|renew\w*)|refresh\W+(?:\w+\W+){0,2}(?:tokens?|sessions?)|session\s+(?:expir\w*|timeout|cookie|fixation|hijack\w*)|(?:user|login|auth)\s+sessions?)\b/i, ids: ['backend-auth'], reason: 'Identity or session lifecycle' },
  { test: /\b(?:dialog|combobox|date\s+picker|datepicker)\b|\bcomponents?\b[\s\S]*\b(?:react|vue|svelte|button|modal|props|render\w*|jsx|tsx|storybook|focus|keyboard|dropdown|selector|widget|reusable)\b|\b(?:react|vue|svelte|button|modal|props|jsx|tsx|storybook|dropdown|selector|widget|reusable)\b[\s\S]*\bcomponents?\b/i, ids: ['react-component'], reason: 'Component interaction contract' },
  // Races: client requests versus competing server-side writes.
  { name: 'race-client', test: /\b(?:race|stale|out.of.order|late\s+response|older\s+requests?)\b[\s\S]*\b(?:component|hook|useeffect|render\w*|typeahead|search\s+box|page|screen|dropdown|selector|tab)\b|\b(?:component|hook|useeffect|typeahead|search\s+box|selector)\b[\s\S]*\b(?:race|stale|out.of.order|late\s+response)\b/i, ids: ['react-async'], reason: 'Client request ordering' },
  { name: 'race-server', test: /\b(?:race|double\s+(?:booking|charge|spend)|lost\s+update|(?:two|concurrent|simultaneous|parallel)\s+(?:requests?|writes?|workers?|updates?|users?))\b[\s\S]*\b(?:row|table|transaction|database|db|balance|stock|inventory|order|webhook|worker|endpoint|job|queue)\b|\b(?:row|table|transaction|database|balance|inventory|webhook|worker|job)\w*\b[\s\S]*\b(?:race|same\s+time|simultaneous\w*|concurrent\w*)\b/i, ids: ['backend-concurrency'], reason: 'Competing server-side writes' },
  { unlessRules: ['race-client', 'race-server'], test: /\b(?:race|stale|out.of.order)\b[\s\S]*\b(?:request|response|fetch)|\b(?:request|response|fetch)\b[\s\S]*\b(?:race|stale|out.of.order)\b/i, ids: ['react-async', 'backend-concurrency'], reason: 'Request ordering and ownership' },
  { test: /\b(?:slow|lag(?:gy|s)?|freez\w*|jank\w*|sluggish)\b[\s\S]*\b(?:component|render\w*|re-?render\w*|keystroke|typing|input|scroll\w*|list|grid|table|page|browser|react)\b|\b(?:component|re-?render\w*|keystroke|typing|scroll\w*|grid)\b[\s\S]*\b(?:slow|lag\w*|freez\w*|jank\w*|sluggish|re-?render\w*)\b|\bre-?render(?:s|ing|ed)?\s+on\s+every\b/i, unlessText: SERVER_WORDS, ids: ['react-rerenders'], reason: 'Slow UI interaction' },
  { test: /\b(?:train\w*)\b[\s\S]*\b(?:serving|inference)\b[\s\S]*\b(?:transform\w*|preprocess\w*|features?|mismatch\w*|skew|parity|differ\w*)\b|\b(?:transform\w*|preprocess\w*|features?)\b[\s\S]*\btrain\w*\b[\s\S]*\b(?:serving|inference)\b|\btraining.serving\s+skew\b/i, ids: ['ml-parity'], reason: 'Training and serving preprocessing parity' },
  { test: /\b(?:offline|validation|notebook|backtest\w*)\b[\s\S]*\b(?:production|prod|serving|live|online)\b|\b(?:production|prod|serving)\b[\s\S]*\b(?:doesn't|does\s+not|don't|won't)\s+match\b/i, ids: ['ml-parity', 'ml-leakage', 'ml-drift'], reason: 'Offline versus serving mismatch' },
  { test: /\b(?:target|label|data|train\w*|test|feature)\s+leak\w*|\bleak\w*\b(?=[\s\S]*\b(?:train\w*|test\s+set|validation|holdout|labels?|features?|model|dataset|split|target|future)\b)|\bcontaminat\w*\b[\s\S]*\b(?:train\w*|test|eval\w*|benchmark)\b|\b(?:suspiciously\s+(?:high|good)|too\s+good\s+to\s+be\s+true|future\s+information|look.?ahead)\b|\bpoint.in.time\b(?!\s*(?:recovery|restore|backup|snapshot))[\s\S]*\b(?:feature|label|training|join|dataset|split)|\b(?:feature|label|training|join|dataset|split)\w*\b[\s\S]*\bpoint.in.time\b(?!\s*(?:recovery|restore|backup|snapshot))/i, unlessText: /\b(?:memory|secrets?|credentials?|api\s+keys?|passwords?|tokens?|connections?|file\s+descriptors?|goroutines?|resources?|handles?|pii|personal\s+data|between\s+(?:accounts|users|tenants|customers)|cache\w*|responsibilit\w*|abstraction)\b/i, ids: ['ml-leakage', 'ml-features'], reason: 'Prediction-time information boundary' },
  { action: true, test: /\brestor\w*\s+(?:\w+\s+){0,3}(?:to\s+)?(?:a\s+)?point.in.time\b|\b(?:point.in.time\s+(?:recovery|restore)|pitr|restore\s+(?:from|the|a|our)\s+(?:\w+\s+)?(?:backup|snapshot)|backups?\b[\s\S]*\brestor\w*|restor\w*\b[\s\S]*\bbackups?\b)/i, ids: ['ops-restore'], reason: 'Backup restoration' },
  { test: /\b(?:train|training)\b[\s\S]*\b(?:resume|checkpoint|interrupt\w*|crashed|stopped)|\b(?:resume|checkpoint)\b[\s\S]*\b(?:train|training)\b/i, ids: ['ml-train', 'ml-reproduce'], reason: 'Training continuation state' },
  { test: /^(?=[\s\S]*\b(?:vercel|vercel\.json|vercel\.app|dpl_\w+)\b)(?=[\s\S]*\b(?:build\w*|deploy\w*)\b)(?=[\s\S]*\b(?:fail\w*|broken|breaks?|errors?|crash\w*)\b)/i, ids: ['vercel-build-fix'], reason: 'Vercel build failure' },
  { test: /\b(?:migrations?|schema\s+changes?|alter\s+table|(?:add|drop)\s+(?:a\s+)?(?:\w+\s+)?columns?)\b(?=[\s\S]*\b(?:schema|tables?|columns?|database|db|sql|postgres\w*|mysql|sqlite|alembic|prisma|flyway|liquibase|knex|sequelize|typeorm|django|rails|index\w*|non-null|nullable|constraints?|rows?|downtime)\b)|\b(?:schema|tables?|columns?|database|db|sql|postgres\w*|mysql|alembic|prisma|flyway|liquibase)\b[\s\S]*\b(?:migrations?|schema\s+changes?)\b/i, unlessRules: ['db-locks'], ids: ['db-migrate'], reason: 'Schema rollout and recovery' },
  { name: 'db-locks', test: /\bdeadlock\w*|\block\s+(?:wait|timeout|contention|queue)s?\b|\bwaiting\s+(?:on|for)\s+(?:a\s+|the\s+)?locks?\b|\b(?:stuck|hang\w*|hung|blocked)\b[\s\S]{0,30}\blocks?\b|\bblocking\s+(?:query|queries|session|transaction)s?\b|\blocked\s+(?:table|rows?)\b/i, ids: ['db-locks'], reason: 'Lock waits or deadlocks' },
  { name: 'vite-upgrade', test: /\bvite\b[\s\S]*\b(?:upgrade|migrat\w*|major\s+version|v?\d+)\b|\b(?:upgrade|migrat\w*)\b[\s\S]*\bvite\b/i, ids: ['vite-upgrade'], reason: 'Vite major-version upgrade' },
  { unlessRules: ['vite-upgrade'], test: /\b(?:upgrade|migrate|port|move\s+off|switch\s+from|replace)\b[\s\S]*\b(?:to|from|with)\b[\s\S]*(?:\bv?\d+(?:\.\d+)*\b|\b(?:version|framework|library|react|vue|angular|next(?:\.js)?|nextjs|django|rails|express|node|python|java|spring|webpack|vite|jest|vitest|typescript|moment|lodash|date-fns|tailwind)\b)|\bv?\d+(?:\.\d+)*\s+to\s+v?\d+(?:\.\d+)*\b/i, unlessText: /\b(?:dependenc\w*|packages?|lockfile|database|schema|tables?)\b/i, ids: ['migrate'], reason: 'Library, framework or runtime migration' },
  { test: /\b(?:bump|update|upgrade)\b[\s\S]*\b(?:dependenc\w*|packages?|lockfile|npm|pnpm|yarn|pip|poetry|renovate)\b|\boutdated\s+(?:packages|dependencies|deps)\b|^(?:please\s+)?bump\s+(?!(?:the\s+|our\s+)?(?:version|release)\b(?!\s+of\b))\w+/i, unlessText: /\b(?:vulnerab\w*|cve\S*|advisor\w*|dependabot\s+alert|security)\b/i, ids: ['deps'], reason: 'Dependency update' },
  { test: /\bbump\s+(?:the\s+|our\s+)?(?:version|release)\b(?!\s+of\b)|\bversion\s+bump\b|\bchangelog\b/i, ids: ['release'], reason: 'Local release preparation' },
  // An authorized mitigation during an incident: roll back, restart, drain or fail over with explicit go-ahead or incident context.
  { test: /\b(?:roll\s*back|restart|drain|fail\s*over)\b[\s\S]*\b(?:go-?ahead|authoriz\w*|approved?|incident|outage|sev\s*[0-4]|on-?call)\b|\b(?:go-?ahead|authoriz\w*|approved?|incident|outage|sev\s*[0-4]|on-?call)\b[\s\S]*\b(?:roll\s*back|restart|drain|fail\s*over)\b/i, ids: ['ops-incident', 'deploy'], reason: 'Authorized incident mitigation' },
  // A feed, file or partition that arrives empty, late or incomplete is a data freshness/completeness problem.
  { test: /\b(?:feed|file|export|partition|extract|load|batch|snapshot)s?\b[\s\S]{0,40}\b(?:arriv\w*|lands?|comes?\s+in|shows?\s+up)\s+(?:empty|late|incomplete|partial|stale)\b|\b(?:empty|late|stale|incomplete)\s+(?:daily\s+|nightly\s+|hourly\s+)?(?:feeds?|partitions?|extracts?|exports?)\b/i, ids: ['data-quality', 'data-pipeline'], reason: 'Data freshness or completeness' },
  { test: /\b(?:model|classifier|ranker|recommender|embedding)s?\b[\s\S]*\b(?:roll(?:ing)?\s*out|rollout|canary|shadow\s+mode|a\/b\s+test|% of traffic)\b|\b(?:roll(?:ing)?\s*out|rollout|canary|shadow\s+mode)\b[\s\S]*\b(?:model|classifier|ranker|recommender)s?\b/i, ids: ['ml-rollout'], reason: 'Staged model rollout' },
  { test: /\b(?:roll(?:ing)?\s*out|rollout|ship|deploy\w*|release|promote)\b[\s\S]*\b(?:production|prod|staging|live)\b|\b(?:production|prod|staging)\b[\s\S]*\b(?:roll(?:ing)?\s*out|rollout|deploy\w*)\b|\bcanary\s+(?:release|deploy\w*|rollout)\b/i, unlessText: /\b(?:model|classifier|ranker|recommender|vercel|migration|schema)\b/i, ids: ['deploy'], reason: 'Deploy to an environment' },
  // A rollout or canary of a service, app or build is a deployment; a model version is ml-rollout.
  { test: /\b(?:roll(?:ing)?\s*out|rollout|canary|blue.green|traffic\s+shift\w*)\b[\s\S]*\b(?:services?|api|backend|frontend|app|build|servers?|site|web\s*app|release)\b|\b(?:services?|api|backend|frontend|app|build|servers?|release)\b[\s\S]*\b(?:roll(?:ing)?\s*out|rollout|canary)\b/i, unlessText: /\b(?:model|classifier|ranker|recommender|embedding|feature\s+flags?)\b/i, ids: ['deploy'], reason: 'Service rollout or canary' },
  { test: /\b(?:partial|staged|unstaged|only\s+these|selected\s+files)\b[\s\S]*\bcommit|\bcommit\b[\s\S]*\b(?:partial|staged|unstaged|only\s+these|selected\s+files)\b/i, ids: ['git-commit', 'git-split'], reason: 'Commit scope and index preservation' },
];

export function matchIntents(text) {
  const matched = intents.filter(rule => rule.test.test(text) && !rule.unlessText?.test(text));
  const names = new Set(matched.map(rule => rule.name).filter(Boolean));
  return matched.filter(rule => !rule.unlessRules?.some(name => names.has(name)));
}
